steps:
  # Build Backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/whatic/backend:$COMMIT_SHA', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/whatic/backend:latest', './backend']

  # Push Backend to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/whatic/backend:latest']

  # Build Frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--build-arg', 'REACT_APP_BACKEND_URL=https://whatic-api-gen-lang-client-0297704847.a.run.app', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/whatic/frontend:$COMMIT_SHA', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/whatic/frontend:latest', './frontend']

  # Push Frontend to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/whatic/frontend:latest']

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/whatic/backend:latest'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/whatic/frontend:latest'
